FROM php:8.1-cli

# Установка необходимых расширений
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    && docker-php-ext-install pdo pdo_mysql

# Установка Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Копируем код и устанавливаем зависимости
COPY . /app
WORKDIR /app
RUN composer install

# Запускаем тесты
CMD ["vendor/bin/phpunit"]